# ==========================================================================
# Project:   NestedRecordsTest
# Copyright: @2011 My Company, Inc.
# ==========================================================================

# This is your Buildfile for your app, NestedRecordsTest. This tells SproutCore
# how to build your app. These settings override those in your project
# Buildfile, which contains default settings for all apps in your project.
#
# This line tells SproutCore's CSS preprocessor what class names to target.
# Since your app has a theme named 'nested-records-test', and it is based on SproutCore's
# Ace theme (named 'ace'), it is set to 'ace.nested-records-test'.
config :nested_records_test, :css_theme => 'ace.nested-records-test'

